#!/bin/bash

cmake -H. -B$BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DWITH_WERROR:BOOL="0" -DBuildTests:BOOL="0" -DSKIP_PORTABILITY_TEST:BOOL="1" -DDOCTEST_WITH_TESTS:BOOL="0" \
    -DJUST_INSTALL_CEREAL:BOOL="1" -DTHREAD_SAFE:BOOL="1" $CMAKE_OPTIONS 