#!/bin/bash

cmake -H. -B$BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DENABLE_COVERAGE:BOOL=TRUE -DSKIP_PORTABILITY_TEST:BOOL=TRUE -DBuildTests:BOOL=FALSE \
    -DWITH_CPP11:BOOL=TRUE -DJUST_INSTALL_CEREAL:BOOL=TRUE \
    -DUTPP_INCLUDE_TESTS_IN_BUILD:BOOL=FALSE -DDOCTEST_WITH_TESTS:BOOL=FALSE \
    -DTEST_MODE:STRING="COMPARE" -DTHEAD_SAFE:BOOL=TRUE $CMAKE_OPTIONS 